name: Composite Action Demo
on:
  workflow_dispatch:

jobs:
  hello-world-1:
    runs-on: ubuntu-24.04
    name: One usage of the composite action
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: composite-action-instance
        uses: ./06-authoring-actions/composite-action
        with:
          who-to-greet: "from composite action in hello-world-1!"
      - env:
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
        run: echo random-number "$RANDOM_NUMBER"
        shell: bash
  hello-world-2:
    runs-on: ubuntu-24.04
    name: Another usage of the composite action
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: composite-action-instance
        uses: ./06-authoring-actions/composite-action
        with:
          who-to-greet: "from composite action in hello-world-2!"
      - env:
          RANDOM_NUMBER: ${{ steps.composite-action-instance.outputs.random-number }}
        run: echo random-number "$RANDOM_NUMBER"
        shell: bash
